### ISSUE TITLE
为啥这代码抄完都不带改的？！！人家ACNet代码写得烂，你还跟着烂？

### ISSUE THREAD

**Issue by oldfashionking** [zhouhao94/CANet#1]

**Comment by zhouqunbing** [comment]
啥意思

**Comment by oldfashionking** [comment]
感觉这个网络名字得改改吧&nbsp;感觉看起来不是特别好&nbsp; ACNet是在你们前面发的吧&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月21日(星期四) 晚上7:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zhouhao94/CANet] 为啥这代码抄完都不带改的？！！人家ACNet代码写得烂，你还跟着烂？ (Issue #1)





 
啥意思
